export enum CookieType {
  ResetPassword = 'reset-token',
  ConfirmEmail = 'confirm-email',
  WhiteList = 'white-list',
  PersonalInformation = 'personal-info',
  BusinessInformation = 'business-info',
  TwoFA = '2fa-email',
  UnverifiedEmail = 'unverified-email',
  UserInfo = 'user-info',
  Token = 'token',
  CollectInfo = 'collection-information',
  ClientDetails = 'client-details',
  MerchantId = 'client-details-',
  CollectionAccounts = 'collection-accounts',
  Splits = 'splits',
  AccountBan = 'account-ban',
  CurrentUrl = 'current-url',
  ExpiryMessage = 'expiry-message',
  LINKED_ACCOUNT_ID = 'LINKED_ACCOUNT_ID',
  PaymentSetup = 'payment-setup',
}
